name: calling-workflow-test
on:
  push:
    branches: [main]

jobs:
  calling:
     uses: ./.github/workflows/called.yml
     with:
       info: "hello"
  outputjob:
    needs: calling
    runs-on: ubuntu-latest
    run:
      echo "${{ needs.calling.output.OUTVALUE }}"
