name: called workflow
on:
  workflow_call:
    inputs:
      info:
        required: true
        description: "info to be sent"
        type: string
    outputs:
      OUTVALUE:
        value: ${{ jobs.called-job.outputs.OUTVALUE }}
jobs:
  called-job:
    runs-on: ubuntu-latest
    outputs:
      OUTVALUE: ${{ steps.INOUT.outputs.FEEDBACK }}
    steps:
      - name: getting input from called worflow
        id: INOUT
        run: |
          echo "the value is ${{ inputs.info }}"
          echo "FEEDBACK=ROCKY" >> $GITHUB_OUTPUT

      - name: print output
        run:
          echo "${{ steps.INOUT.outputs.FEEDBACK }}"

  test-job:
    needs: called-job
    runs-on: ubuntu-latest
    steps:
      - name: output previous job
        run:
          echo "${{ needs.called-job.outputs.OUTVALUE }}"
      
