name: test variables and env
on:
  push:

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: execute code
        run: |
          chmod +x myfirstbash.sh
          bash myfirstbash.sh
     
