name: test variables and env
on:
  push:

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: test env
        env:
          test_var: "hello"
        run: echo "$test_var"
        
     
