name: testing exit status
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: step_1
        run: exit 1
        if: contains(runner.os,'linux')
      - name: step_2
        run: echo "hi"
        if: failure()
        continue-on-error: true
      - name: step_3
        run: echo "hello"
        
